-- Narrow feature surface for live / near-real-time scoring (downstream ML daemon).
-- Omits final scrap labels and rollup scrap fields to avoid training-serving skew when
-- the model is only allowed pre-outcome process features. Full labels stay on v_ml_heat_dataset_v1.
-- Companion to 067_ml_heat_dataset.sql (Spuncast-Operations / 097_ml_heat_early_score_view.sql).

CREATE OR REPLACE VIEW v_ml_heat_early_score_v1 AS
SELECT
    heat_id,
    heat_number,
    product_number,
    feature_cutoff_ts,
    alloy_grade,
    grade_name,
    chemistry_grade,
    pour_date,
    shift,
    job_number,
    stock_code,
    spec_code,
    furn_no,
    die_no,
    melter,
    cmop,
    analysis_equipment_code,
    operator_id,
    heat_start_ts,
    heat_end_ts,
    heat_created_at,
    pour_entered_at,
    heat_treat_start_ts,
    heat_treat_end_ts,
    chem_last_tested_at,
    tap_temp_missing,
    pour_temp_missing,
    die_temp_missing,
    die_rpm_missing,
    spec_code_missing,
    stock_code_missing,
    die_no_missing,
    tap_minus_pour_temp,
    tap_minus_die_temp,
    pour_minus_die_temp,
    chem_not_ok_flag,
    has_any_chem_alert,
    heat_treat_operator_id,
    heat_treat_temp_delta,
    lot_count,
    latest_lot_date,
    tap_temp,
    pour_temp,
    die_temp_before_pour,
    die_rpm,
    spin_time_min,
    pour_time_sec,
    cr_pct,
    tap_pct_of_band,
    pour_pct_of_band,
    die_pct_of_band,
    rpm_deviation_pct,
    chem_element_count,
    chem_ok_count,
    chem_low_count,
    chem_high_count,
    chem_missing_spec_count,
    chem_no_spec_count,
    chem_heat_status,
    pour_heat_status,
    pour_rpm_status,
    equipment_code,
    cycle_name,
    setpoint_temp_f,
    actual_temp_f,
    quantity_produced,
    quantity_shipped,
    quantity_on_hold,
    has_open_data_quality_violation,
    open_data_quality_violation_count,
    latest_decision_code,
    latest_risk_score,
    instruction_source,
    tap_deviation_from_instruction_pct,
    pour_deviation_from_instruction_pct,
    die_deviation_from_instruction_pct,
    rpm_deviation_from_instruction_pct
FROM v_ml_heat_dataset_v1;

COMMENT ON VIEW v_ml_heat_early_score_v1 IS
    'Pre-outcome feature slice for live scoring; includes cr_pct (latest Cr reading) and '
    'instruction deviation columns (tap/pour/die/rpm_deviation_from_instruction_pct, instruction_source) '
    'from correctly-scoped process_control_profiles. '
    'Excludes scrap_flag, reason_code, defect_type, scrap_estimated_cost, analysis_date, '
    'has_scrap, latest_scrap_ts, reason_code_bucket, and all post-outcome scrap diagnostics.';
