-- ml_heat_scores DDL is owned by Operations (db/init/122_ml_heat_scores_contract.sql).
-- Do not define this table in the ML repo; it is guaranteed to exist after
-- ./scripts/apply_db_init.sh runs in the Operations repo.
-- The live scoring daemon (scripts/score_heat_live.py) INSERTs only.
