-- Operator-facing recommendations generated by the live scoring daemon.
-- Rows are inserted by score_heat_live.py when a heat exceeds the re-melt
-- threshold.  Operators act on these via the Grafana dashboard or the
-- pour-log portal.

CREATE TABLE IF NOT EXISTS heat_recommendations (
    id                   BIGSERIAL    PRIMARY KEY,
    heat_number          TEXT         NOT NULL UNIQUE,
    decision_code        TEXT         NOT NULL DEFAULT 'HOLD',
    recommendation_text  TEXT,
    primary_driver       TEXT,
    scrap_probability    FLOAT,
    feature_set          TEXT         NOT NULL DEFAULT 'early_remelt_decision',
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    resolved_at          TIMESTAMPTZ,
    resolved_by          TEXT
);

CREATE INDEX IF NOT EXISTS idx_hr_heat
    ON heat_recommendations (heat_number);

CREATE INDEX IF NOT EXISTS idx_hr_created
    ON heat_recommendations (created_at DESC);
