-- explanation_json is no longer part of the ml_heat_scores contract.
-- SHAP payloads are now written to the metadata JSONB column by
-- scripts/score_heat_live.py.  This file should not be applied.
